name: RPGItems
main: com.aoideveloper.rpg_items.RPGItems
version: 1.0
api-version: 1.16
commands:
  rpgitems:
    description: RPG Itemsについてのコマンドを実行できます。
    usage: |
        /<command> give <player> <itemId> プレイヤーにアイテムを与えます。
        /<command> descript <itemId> アイテムの説明を表示します。
        /<command> reload アイテムの設定をリロードします。
    permission: op